name: Python 应用测试

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 语法检查
      run: |
        python -m py_compile daily_planner.py
        python -m py_compile daily_planner_cli.py
        python -m py_compile web_server.py
        python -m py_compile launcher.py
    
    - name: 运行基本测试
      run: |
        python -c "import daily_planner; print('GUI模块导入成功')"
        python -c "import daily_planner_cli; print('CLI模块导入成功')"
        python -c "import web_server; print('Web服务器模块导入成功')"
